In [ ]:
import geopandas as gpd
import numpy as np
import json
import pandas as pd

In [ ]:
us = gpd.read_file('Data/US_fixed.shp')

In [ ]:
growth = pd.read_csv('https://www2.census.gov/programs-surveys/popest/datasets/2010-2020/counties/totals/co-est2020-alldata.csv', encoding = 'latin-1')

In [ ]:
growth.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,RNETMIG2016,RNETMIG2017,RNETMIG2018,RNETMIG2019,RNETMIG2020
0,40,3,6,1,0,Alabama,Alabama,4779736,4780118,4785514,...,0.680010,1.282825,1.614391,0.653828,0.730419,0.854384,1.197150,1.966095,2.677866,3.091308
1,50,3,6,1,1,Alabama,Autauga County,54571,54582,54761,...,6.236931,-5.971016,-3.773344,2.206640,-1.529706,4.954403,0.993228,-0.018021,3.486011,6.290545
2,50,3,6,1,3,Alabama,Baldwin County,182265,182263,183121,...,16.705437,17.670696,22.924288,20.300088,17.902273,21.436499,22.476720,24.846335,25.242507,26.401562
3,50,3,6,1,5,Alabama,Barbour County,27457,27454,27325,...,0.329254,-6.860371,-8.093425,-5.063857,-15.677998,-18.377839,-25.138734,-8.790155,-6.257064,0.649799
4,50,3,6,1,7,Alabama,Bibb County,22915,22904,22858,...,-4.912927,-3.789130,-5.800695,1.420612,1.286202,-0.841769,-3.235672,-7.271592,0.268980,-7.199262

In [ ]:
years = [i for i in range(2010,2021)]

In [ ]:
names = [f'POPESTIMATE{year}' for year in years]

In [ ]:
other = [f'NETMIG{year}' for year in years]

In [ ]:
columns = ['SUMLEV', 'REGION', 'DIVISION', 'STATE', 'COUNTY', 'STNAME', 'CTYNAME',
       'CENSUS2010POP', 'ESTIMATESBASE2010']

In [ ]:
for name in names:
    columns.append(name)
for mi in other:
    columns.append(mi)

In [ ]:
counties = growth[columns]

In [ ]:
intervals = [1,2,3,5, 10]

In [ ]:
for i in intervals:
    col = f'{i} years'
    growth[col] = (growth['POPESTIMATE2020']-growth[f'POPESTIMATE{2020-i}'])/growth[f'POPESTIMATE{2020-i}']

In [ ]:
growth.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RNETMIG2016,RNETMIG2017,RNETMIG2018,RNETMIG2019,RNETMIG2020,1 years,2 years,3 years,5 years,10 years
0,40,3,6,1,0,Alabama,Alabama,4779736,4780118,4785514,...,0.854384,1.197150,1.966095,2.677866,3.091308,0.002764,0.006113,0.008926,0.013745,0.028423
1,50,3,6,1,1,Alabama,Autauga County,54571,54582,54761,...,4.954403,0.993228,-0.018021,3.486011,6.290545,0.006742,0.011020,0.012570,0.022622,0.025273
2,50,3,6,1,3,Alabama,Baldwin County,182265,182263,183121,...,21.436499,22.476720,24.846335,25.242507,26.401562,0.025594,0.051433,0.077796,0.128931,0.252107
3,50,3,6,1,5,Alabama,Barbour County,27457,27454,27325,...,-18.377839,-25.138734,-8.790155,-6.257064,0.649799,-0.002758,-0.011974,-0.023044,-0.065057,-0.100128
4,50,3,6,1,7,Alabama,Bibb County,22915,22904,22858,...,-0.841769,-3.235672,-7.271592,0.268980,-7.199262,-0.007933,-0.007354,-0.017575,-0.018490,-0.031586

In [ ]:
one = growth.sort_values('3 years').tail(15)
one

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RNETMIG2016,RNETMIG2017,RNETMIG2018,RNETMIG2019,RNETMIG2020,1 years,2 years,3 years,5 years,10 years
2849,50,4,8,49,53,Utah,Washington County,138115,138115,138397,...,24.454793,34.961256,30.628596,29.252348,34.752557,0.039199,0.074757,0.112627,0.194228,0.336106
111,50,4,8,4,21,Arizona,Pinal County,375770,375766,379106,...,23.973743,30.141305,31.215903,30.730132,39.008221,0.041565,0.076825,0.114343,0.184533,0.268321
2833,50,4,8,49,21,Utah,Iron County,46163,46163,46264,...,22.548789,12.810455,30.105002,33.429427,19.075150,0.027954,0.072792,0.115225,0.179546,0.228039
2672,50,3,7,48,209,Texas,Hays County,157107,156978,158086,...,42.613530,42.284548,30.023459,26.740020,40.935635,0.047591,0.082704,0.123344,0.240390,0.526796
396,50,3,5,12,131,Florida,Walton County,55043,55044,55214,...,33.599465,37.006542,38.249007,43.792801,32.180401,0.034009,0.081469,0.125356,0.213841,0.388199
476,50,3,5,13,157,Georgia,Jackson County,60485,60470,60706,...,22.127130,35.112825,34.992900,33.425873,40.183897,0.043607,0.083188,0.125855,0.201138,0.255214
2813,50,3,7,48,491,Texas,Williamson County,422679,422771,426568,...,31.917060,27.623055,30.383146,35.885820,37.133849,0.043986,0.088798,0.129871,0.216902,0.448433
2766,50,3,7,48,397,Texas,Rockwall County,78337,78398,78971,...,30.146271,30.535072,32.883147,37.380630,42.831199,0.047930,0.092413,0.133380,0.217488,0.391498
1934,50,3,5,37,19,North Carolina,Brunswick County,107431,107429,108070,...,35.691313,38.909478,49.435402,45.711960,47.112243,0.042326,0.087312,0.137737,0.218415,0.379097
385,50,3,5,12,109,Florida,St. Johns County,190039,190040,191268,...,36.078255,36.598165,39.295366,42.340702,50.718761,0.051485,0.097273,0.141961,0.230084,0.457196
2078,50,2,4,38,105,North Dakota,Williams County,22398,22399,22591,...,-44.556090,-33.213103,45.661047,44.459542,5.404911,0.021189,0.084094,0.150450,0.093869,0.713072
2696,50,3,7,48,257,Texas,Kaufman County,103350,103352,103880,...,27.468196,33.788358,39.766780,54.564462,42.966920,0.049385,0.114277,0.166554,0.255209,0.378494
2613,50,3,7,48,91,Texas,Comal County,108472,108525,109311,...,38.347298,44.022986,50.513755,51.978403,50.577904,0.053549,0.111867,0.171197,0.278901,0.507735
2052,50,2,4,38,53,North Dakota,McKenzie County,6360,6359,6412,...,-30.368593,-4.423555,51.490721,87.144904,-0.396301,0.013566,0.122303,0.198742,0.189202,1.377105
2718,50,3,7,48,301,Texas,Loving County,82,82,84,...,-33.898305,152.000000,92.198582,101.910828,92.485549,0.096970,0.214765,0.360902,0.521008,1.154762

def join(state, county, inter, df = growth):
    df1 = df.loc[df['STNAME'] == state]
    df1.set_index('CTYNAME', inplace = True)
    col = f"{inter} year'
    return df1.loc['county' ]

In [ ]:
us.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1737905 entries, 0 to 1737904
Data columns (total 25 columns):
 #   Column      Dtype
---  ------      -----
 0   quadkey     object
 1   avg_d_kbps  int64
 2   avg_u_kbps  int64
 3   avg_lat_ms  int64
 4   tests       int64
 5   devices     int64
 6   index_righ  int64
 7   STATEFP     object
 8   COUNTYFP    object
 9   COUNTYNS    object
 10  GEOID       object
 11  NAME        object
 12  NAMELSAD    object
 13  LSAD        object
 14  CLASSFP     object
 15  MTFCC       object
 16  CSAFP       object
 17  CBSAFP      object
 18  METDIVFP    object
 19  FUNCSTAT    object
 20  ALAND       int64
 21  AWATER      int64
 22  INTPTLAT    object
 23  INTPTLON    object
 24  geometry    geometry
dtypes: geometry(1), int64(8), object(16)
memory usage: 331.5+ MB

In [ ]:
us['NAMELSAD']

0                        Comal County
1                        Comal County
2                        Comal County
3                        Comal County
4                        Comal County
                      ...
1737900               Garfield County
1737901               Garfield County
1737902              McPherson County
1737903               Marshall County
1737904    Aleutians West Census Area
Name: NAMELSAD, Length: 1737905, dtype: object

In [ ]:
metros = gpd.read_file('Data/metro_areas.csv')
#states = gpd.read_file('Data/)

In [ ]:
metros.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Metro Area                     125 non-null    object
 1   Est. 2019 Population           125 non-null    object
 2   Average Annual Salary          125 non-null    object
 3   ZORI 2020-06                   125 non-null    object
 4   Avg Annual Rainfall            125 non-null    object
 5   Lowest Monthly Avg High Temp   125 non-null    object
 6   Highest Monthly Avg High Temp  125 non-null    object
 7   Violent Crime Rate             125 non-null    object
 8   Property Crime Rate            125 non-null    object
 9   U.S. News Overall Score        125 non-null    object
 10  U.S. News State Overall Rank   125 non-null    object
 11  Nomad Score 2019-12-21T17:00Z  125 non-null    object
 12  Nomad Score 2020-06-14T06:30Z  125 non-null    object
 13  Nomad Score 2020-06-14T19:11Z  125 non-null    object
 14  Nomad Score 2020-08-16T06:48Z  125 non-null    object
 15  Nomad Score 2020-08-16T19:13Z  125 non-null    object
 16  Data Scientist Job Postings    125 non-null    object
 17  geometry                       0 non-null      geometry
dtypes: geometry(1), object(17)
memory usage: 17.7+ KB

In [ ]:
states = gpd.read_file('Data/state_ranks.csv')

In [ ]:
metpop = pd.read_csv('https://www2.census.gov/programs-surveys/popest/datasets/2010-2020/metro/totals/csa-est2020-alldata.csv', encoding = 'latin-1')

In [ ]:
metpop.columns

Index(['CSA', 'CBSA', 'MDIV', 'STCOU', 'NAME', 'LSAD', 'CENSUS2010POP',
       'ESTIMATESBASE2010', 'POPESTIMATE2010', 'POPESTIMATE2011',
       ...
       'RESIDUAL2011', 'RESIDUAL2012', 'RESIDUAL2013', 'RESIDUAL2014',
       'RESIDUAL2015', 'RESIDUAL2016', 'RESIDUAL2017', 'RESIDUAL2018',
       'RESIDUAL2019', 'RESIDUAL2020'],
      dtype='object', length=107)

In [ ]:
columns = ['CSA', 'CBSA', 'MDIV', 'STCOU', 'NAME', 'LSAD']
mig= [f'NETMIG{year}' for year in years]
for name in names:
    columns.append(name)
for mi in mig:
    columns.append(mi)

In [ ]:
metpop = metpop[columns]

In [ ]:
metpop.head()

,CSA,CBSA,MDIV,STCOU,NAME,LSAD,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,...,NETMIG2011,NETMIG2012,NETMIG2013,NETMIG2014,NETMIG2015,NETMIG2016,NETMIG2017,NETMIG2018,NETMIG2019,NETMIG2020
0,104,NaN,NaN,NaN,"Albany-Schenectady, NY",Combined Statistical Area,1168928,1169287,1170442,1171438,...,-896,38,-69,-1300,-1112,-1812,1349,-268,-3816,-1919
1,104,10580.0,NaN,NaN,"Albany-Schenectady-Troy, NY",Metropolitan Statistical Area,871101,872870,874851,877282,...,315,642,1079,-452,-205,-541,1508,-77,-3217,-1096
2,104,10580.0,NaN,36001.0,"Albany County, NY",County or equivalent,304085,304627,305776,306661,...,143,905,395,47,-210,-196,-256,-1350,-2003,-977
3,104,10580.0,NaN,36083.0,"Rensselaer County, NY",County or equivalent,159342,159606,159466,159590,...,31,-352,20,-119,-410,-312,-230,172,-528,-723
4,104,10580.0,NaN,36091.0,"Saratoga County, NY",County or equivalent,220123,221136,222527,224151,...,528,864,1107,-97,1120,610,1855,790,-506,911

In [ ]:
prices = pd.read_csv('Data/County_zhvi_uc_sfr_tier_0.33_0.67_sm_sa_month.csv')

In [ ]:
current_prices = prices['2021-10-31']

In [ ]:
current_prices

0       838224.0
1       299379.0
2       254593.0
3       436614.0
4       859724.0
          ...
2816    190904.0
2817    276600.0
2818    394449.0
2819    345172.0
2820    364508.0
Name: 2021-10-31, Length: 2821, dtype: float64

In [ ]:
counties.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,NETMIG2011,NETMIG2012,NETMIG2013,NETMIG2014,NETMIG2015,NETMIG2016,NETMIG2017,NETMIG2018,NETMIG2019,NETMIG2020
0,40,3,6,1,0,Alabama,Alabama,4779736,4780118,4785514,...,3259,6168,7788,3163,3542,4153,5833,9604,13121,15193
1,50,3,6,1,1,Alabama,Autauga County,54571,54582,54761,...,343,-329,-207,121,-84,273,55,-1,194,352
2,50,3,6,1,3,Alabama,Baldwin County,182265,182263,183121,...,3088,3329,4415,4002,3602,4404,4726,5352,5574,5978
3,50,3,6,1,5,Alabama,Barbour County,27457,27454,27325,...,9,-187,-219,-136,-416,-479,-641,-220,-155,16
4,50,3,6,1,7,Alabama,Bibb County,22915,22904,22858,...,-112,-86,-131,32,29,-19,-73,-163,6,-160

In [ ]:
us.head()

,quadkey,avg_d_kbps,avg_u_kbps,avg_lat_ms,tests,devices,index_righ,STATEFP,COUNTYFP,COUNTYNS,...,MTFCC,CSAFP,CBSAFP,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,0231301222133033,166797,55407,18,38,10,703,48,091,01383831,...,G4020,484,41700,None,A,1449162144,39775861,+29.8054913,-098.2605440,"POLYGON ((-98.11340 29.71191, -98.10791 29.711..."
1,0231301222120113,7850,1510,28,4,1,703,48,091,01383831,...,G4020,484,41700,None,A,1449162144,39775861,+29.8054913,-098.2605440,"POLYGON ((-98.22327 29.75961, -98.21777 29.759..."
2,0231301222301320,116315,13823,22,83,20,703,48,091,01383831,...,G4020,484,41700,None,A,1449162144,39775861,+29.8054913,-098.2605440,"POLYGON ((-98.19580 29.65942, -98.19031 29.659..."
3,0231301222311121,143093,15049,23,94,25,703,48,091,01383831,...,G4020,484,41700,None,A,1449162144,39775861,+29.8054913,-098.2605440,"POLYGON ((-98.10242 29.67851, -98.09692 29.678..."
4,0231301222133230,118641,15201,22,36,7,703,48,091,01383831,...,G4020,484,41700,None,A,1449162144,39775861,+29.8054913,-098.2605440,"POLYGON ((-98.11890 29.69760, -98.11340 29.697..."

In [ ]:
abbr = pd.read_csv('Data/stateAbbr.csv')

In [ ]:
abbr.head

<bound method NDFrame.head of                    State  Abbrev Code
0                Alabama    Ala.   AL
1                 Alaska  Alaska   AK
2                Arizona   Ariz.   AZ
3               Arkansas    Ark.   AR
4             California  Calif.   CA
5               Colorado   Colo.   CO
6            Connecticut   Conn.   CT
7               Delaware    Del.   DE
8   District of Columbia    D.C.   DC
9                Florida    Fla.   FL
10               Georgia     Ga.   GA
11                Hawaii  Hawaii   HI
12                 Idaho   Idaho   ID
13              Illinois    Ill.   IL
14               Indiana    Ind.   IN
15                  Iowa    Iowa   IA
16                Kansas   Kans.   KS
17              Kentucky     Ky.   KY
18             Louisiana     La.   LA
19                 Maine   Maine   ME
20              Maryland     Md.   MD
21         Massachusetts   Mass.   MA
22              Michigan   Mich.   MI
23             Minnesota   Minn.   MN
24           Mississippi   Miss.   MS
25              Missouri     Mo.   MO
26               Montana   Mont.   MT
27              Nebraska   Nebr.   NE
28                Nevada    Nev.   NV
29         New Hampshire    N.H.   NH
30            New Jersey    N.J.   NJ
31            New Mexico    N.M.   NM
32              New York    N.Y.   NY
33        North Carolina    N.C.   NC
34          North Dakota    N.D.   ND
35                  Ohio    Ohio   OH
36              Oklahoma   Okla.   OK
37                Oregon    Ore.   OR
38          Pennsylvania     Pa.   PA
39          Rhode Island    R.I.   RI
40        South Carolina    S.C.   SC
41          South Dakota    S.D.   SD
42             Tennessee   Tenn.   TN
43                 Texas    Tex.   TX
44                  Utah    Utah   UT
45               Vermont     Vt.   VT
46              Virginia     Va.   VA
47            Washington   Wash.   WA
48         West Virginia   W.Va.   WV
49             Wisconsin    Wis.   WI
50               Wyoming    Wyo.   WY>

In [ ]:
abbr.set_index('Code', inplace = True)

In [ ]:
def fullname(value, df = abbr):
    full = df.loc[value , 'State']
    return full
prices['StateName'] = prices['State'].apply(lambda x: fullname(x))

In [ ]:
prices.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,2000-01-31,...,2021-01-31,2021-02-28,2021-03-31,2021-04-30,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31
0,3101,0,Los Angeles County,County,California,CA,Los Angeles-Long Beach-Anaheim,6,37,222111.0,...,732123.0,739704.0,747393.0,758617.0,773530.0,792245.0,813221.0,826009.0,835355.0,838224.0
1,139,1,Cook County,County,Illinois,IL,Chicago-Naperville-Elgin,17,31,179081.0,...,272372.0,275025.0,277138.0,280615.0,282667.0,286006.0,289838.0,293876.0,296685.0,299379.0
2,1090,2,Harris County,County,Texas,TX,Houston-The Woodlands-Sugar Land,48,201,116078.0,...,221939.0,224535.0,225800.0,227659.0,229954.0,234925.0,240375.0,246249.0,250738.0,254593.0
3,2402,3,Maricopa County,County,Arizona,AZ,Phoenix-Mesa-Scottsdale,4,13,147256.0,...,349550.0,356202.0,365270.0,372112.0,384712.0,396478.0,410161.0,420448.0,428904.0,436614.0
4,2841,4,San Diego County,County,California,CA,San Diego-Carlsbad,6,73,240519.0,...,719085.0,728055.0,739073.0,754151.0,776744.0,802608.0,828222.0,843946.0,854574.0,859724.0

In [ ]:
us.columns

Index(['quadkey', 'avg_d_kbps', 'avg_u_kbps', 'avg_lat_ms', 'tests', 'devices',
       'index_righ', 'STATEFP', 'COUNTYFP', 'COUNTYNS', 'GEOID', 'NAME',
       'NAMELSAD', 'LSAD', 'CLASSFP', 'MTFCC', 'CSAFP', 'CBSAFP', 'METDIVFP',
       'FUNCSTAT', 'ALAND', 'AWATER', 'INTPTLAT', 'INTPTLON', 'geometry'],
      dtype='object')

In [ ]:
us.STATEFP.unique()

array(['48', '17', '21', '29', '22', '13', '06', '05', '36', '12', '47',
       '18', '09', '33', '04', '28', '27', '08', '24', '39', '41', '16',
       '34', '37', '02', '26', '01', '53', '25', '72', '19', '42', '54',
       '23', '55', '45', '31', '15', '35', '40', '44', '51', '66', '30',
       '49', '32', '46', '20', '60', '10', '56', '11', '50', '78', '38',
       '69'], dtype=object)

In [ ]:
label = gpd.read_file('https://www2.census.gov/geo/tiger/GENZ2019/shp/cb_2019_us_state_500k.zip')

In [ ]:
labels = label[['STATEFP', 'NAME']].set_index('STATEFP').rename(columns={'NAME':'State'})

In [ ]:
labels.columns

Index(['State'], dtype='object')

In [ ]:
us['STATENAME'] = us['STATEFP'].apply(lambda x: fullname(str(x), df = labels))

In [ ]:
stategrowth = pd.read_csv('Data/nst-est2019-alldata.csv')

In [ ]:
stategrowth.head(15)

,SUMLEV,REGION,DIVISION,STATE,NAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,...,RDOMESTICMIG2019,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,RNETMIG2016,RNETMIG2017,RNETMIG2018,RNETMIG2019
0,10,0,0,0,United States,308745538,308758105,309321666,311556874,313830990,...,0.000000,2.493773,2.682083,2.636187,2.921500,3.260435,3.252788,2.871957,2.153911,1.818059
1,20,1,0,0,Northeast Region,55317240,55318443,55380134,55604223,55775216,...,-5.254530,0.887909,-0.038355,-0.469783,-0.986097,-2.061965,-2.490484,-1.837048,-2.134447,-2.859713
2,20,2,0,0,Midwest Region,66927001,66929725,66974416,67157800,67336743,...,-2.365881,-0.963930,-0.973943,-0.006924,-0.762969,-1.388437,-1.241784,-0.557370,-0.922755,-1.111173
3,20,3,0,0,South Region,114555744,114563030,114866680,116006522,117241208,...,3.261349,5.130513,5.850458,5.292073,6.161501,7.277358,7.150074,6.198168,5.225519,5.203720
4,20,4,0,0,West Region,71945553,71946907,72100436,72788329,73477823,...,0.614245,2.723344,3.062896,3.162262,4.026429,4.987285,5.261078,4.021194,3.044951,2.312083
5,40,3,6,1,Alabama,4779736,4780125,4785437,4799069,4815588,...,1.917501,0.578434,1.186314,1.522549,0.563489,0.626357,0.745172,1.090366,1.773786,2.483744
6,40,4,9,2,Alaska,710231,710249,713910,722128,730443,...,-12.929847,0.587728,1.416798,-0.955359,-11.460949,-7.997118,-3.897349,-10.992765,-13.859140,-12.031221
7,40,4,8,4,Arizona,6392017,6392288,6407172,6472643,6554978,...,12.609078,4.278167,6.899802,6.376679,9.168478,9.597577,11.964782,10.878879,12.962934,13.687161
8,40,3,7,5,Arkansas,2915918,2916031,2921964,2940667,2952164,...,0.834503,3.294766,0.827785,0.057853,-0.091449,1.075446,1.486269,2.009593,0.958896,0.923429
9,40,4,9,6,California,37253956,37254519,37319502,37638369,37948800,...,-5.151429,1.276797,1.495016,1.649031,2.203551,1.984957,0.500044,-0.629909,-2.130954,-3.276681
10,40,4,8,8,Colorado,5029196,5029319,5047349,5121108,5192647,...,5.473351,7.795086,7.512104,8.492707,9.117126,12.902098,10.634370,8.032033,9.410633,7.311426
11,40,1,1,9,Connecticut,3574097,3574147,3579114,3588283,3594547,...,-6.181756,0.242487,-0.409588,-1.671074,-1.941757,-3.756242,-4.137741,-2.616537,-1.533419,-2.728391
12,40,3,5,10,Delaware,897934,897937,899593,907381,915179,...,7.179090,4.848991,4.843736,6.150901,6.436204,6.713849,5.382576,6.252676,7.631475,7.254377
13,40,3,5,11,District of Columbia,601723,601767,605226,619800,634924,...,-3.130827,16.246186,16.091188,16.784065,10.637447,12.296969,8.092770,6.538613,3.481678,0.569887
14,40,3,5,12,Florida,18801310,18804564,18845537,19053237,19297822,...,6.268893,8.925935,10.561534,11.079296,13.202431,16.491494,18.258305,15.616389,12.657811,10.420286

In [ ]:
stategrowth = stategrowth.loc[5:]

In [ ]:
stategrowth['totalgrowth'] = stategrowth['POPESTIMATE2019']-stategrowth['POPESTIMATE2010']

In [ ]:
stategrowth['pct_growth'] = stategrowth['totalgrowth']/stategrowth['POPESTIMATE2010']

In [ ]:
stategrowth = stategrowth[['NAME','pct_growth', 'totalgrowth']].set_index('NAME')

In [ ]:
stategrowth.to_csv('Data/Stategrowth.csv')

In [ ]:
stategrowth.head()

            pct_growth  totalgrowth
NAME
Alabama       0.024605       117748
Alaska        0.024702        17635
Arizona       0.136026       871545
Arkansas      0.032800        95840
California    0.058755      2192721

In [ ]:
whole=prices.groupby('StateName').mean()

In [ ]:
whole = whole.join(stategrowth)

In [ ]:
us.columns

Index(['quadkey', 'avg_d_kbps', 'avg_u_kbps', 'avg_lat_ms', 'tests', 'devices',
       'index_righ', 'STATEFP', 'COUNTYFP', 'COUNTYNS', 'GEOID', 'NAME',
       'NAMELSAD', 'LSAD', 'CLASSFP', 'MTFCC', 'CSAFP', 'CBSAFP', 'METDIVFP',
       'FUNCSTAT', 'ALAND', 'AWATER', 'INTPTLAT', 'INTPTLON', 'geometry',
       'STATENAME'],
      dtype='object')

In [ ]:
statespeed = us[['avg_d_kbps', 'avg_u_kbps', 'avg_lat_ms', 'STATENAME']].groupby('STATENAME').mean()

In [ ]:
whole = whole.join(statespeed)

In [ ]:
whole.head()

,RegionID,SizeRank,StateCodeFIPS,MunicipalCodeFIPS,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,...,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,pct_growth,totalgrowth,avg_d_kbps,avg_u_kbps,avg_lat_ms
StateName,,,,,,,,,,,,,,,,,,,,,
Alabama,1617.584615,1268.400000,1.0,67.092308,105493.500000,105693.250000,105862.750000,103730.000000,99907.700000,100165.700000,...,133527.031250,134132.846154,135627.000000,137006.246154,138210.076923,0.024605,117748,92973.566568,31861.669395,56.531290
Alaska,89846.500000,1388.250000,2.0,123.375000,170388.000000,170777.000000,170855.000000,171058.000000,171224.000000,171291.000000,...,327874.875000,329764.500000,331583.875000,333070.000000,334388.875000,0.024702,17635,82159.577149,18233.922596,28.105330
Arizona,1376.533333,728.333333,4.0,13.866667,110560.000000,110748.818182,110933.909091,111359.181818,111846.727273,112365.363636,...,280966.666667,288613.266667,296240.333333,302276.266667,307981.133333,0.136026,871545,94196.491220,20508.692968,42.668622
Arkansas,1602.175676,1707.554054,5.0,75.297297,66486.090909,66634.840909,66759.272727,67020.113636,67236.909091,67417.727273,...,106435.364865,107581.594595,108640.148649,109717.621622,110730.027027,0.032800,95840,76625.262148,28594.584974,63.724063
California,1792.948276,687.034483,6.0,58.000000,254575.000000,255776.517241,257239.586207,260460.068966,264040.241379,267921.344828,...,568288.413793,583218.620690,595610.913793,605189.241379,610681.568966,0.058755,2192721,113506.351358,25765.241946,42.563994

In [ ]:
whole.to_csv('Data/WholeCountry.csv')

In [ ]:
counties=counties.loc[growth['COUNTY'] !=0 ]

In [ ]:
countieslg = counties.loc[counties['POPESTIMATE2010']>10000]

In [ ]:
countieslg.columns

Index(['SUMLEV', 'REGION', 'DIVISION', 'STATE', 'COUNTY', 'STNAME', 'CTYNAME',
       'CENSUS2010POP', 'ESTIMATESBASE2010', 'POPESTIMATE2010',
       'POPESTIMATE2011', 'POPESTIMATE2012', 'POPESTIMATE2013',
       'POPESTIMATE2014', 'POPESTIMATE2015', 'POPESTIMATE2016',
       'POPESTIMATE2017', 'POPESTIMATE2018', 'POPESTIMATE2019',
       'POPESTIMATE2020', 'NETMIG2010', 'NETMIG2011', 'NETMIG2012',
       'NETMIG2013', 'NETMIG2014', 'NETMIG2015', 'NETMIG2016', 'NETMIG2017',
       'NETMIG2018', 'NETMIG2019', 'NETMIG2020'],
      dtype='object')

In [ ]:
countieslg['totalgrowth'] = countieslg['POPESTIMATE2019']-countieslg['POPESTIMATE2010']

/opt/conda/envs/rapids/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
countieslg['pctgrowth'] = countieslg['totalgrowth']/countieslg['POPESTIMATE2010']

/opt/conda/envs/rapids/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [ ]:
countieslg.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,NETMIG2013,NETMIG2014,NETMIG2015,NETMIG2016,NETMIG2017,NETMIG2018,NETMIG2019,NETMIG2020,totalgrowth,pctgrowth
1,50,3,6,1,1,Alabama,Autauga County,54571,54582,54761,...,-207,121,-84,273,55,-1,194,352,1008,0.018407
2,50,3,6,1,3,Alabama,Baldwin County,182265,182263,183121,...,4415,4002,3602,4404,4726,5352,5574,5978,40444,0.220859
3,50,3,6,1,5,Alabama,Barbour County,27457,27454,27325,...,-219,-136,-416,-479,-641,-220,-155,16,-2668,-0.097640
4,50,3,6,1,7,Alabama,Bibb County,22915,22904,22858,...,-131,32,29,-19,-73,-163,6,-160,-545,-0.023843
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57372,...,-16,-115,-75,-70,357,14,54,69,468,0.008157

In [ ]:
propgrowthcty= countieslg.sort_values('pctgrowth').tail(100)

In [ ]:
propgrowthcty

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,NETMIG2013,NETMIG2014,NETMIG2015,NETMIG2016,NETMIG2017,NETMIG2018,NETMIG2019,NETMIG2020,totalgrowth,pctgrowth
1956,50,3,5,37,63,North Carolina,Durham County,267587,269998,271366,...,3656,3869,3295,4693,2192,2914,3457,2585,51603,0.190160
2587,50,3,7,48,39,Texas,Brazoria County,313166,313186,314499,...,3217,5071,4895,5486,6527,4949,3014,3918,60200,0.191416
2531,50,3,6,47,119,Tennessee,Maury County,80956,80986,81230,...,1282,1492,1830,1904,2421,1919,1989,2684,15565,0.191616
605,50,4,8,16,81,Idaho,Teton County,10170,10165,10149,...,163,-78,187,328,178,86,373,346,1947,0.191842
42,50,3,6,1,83,Alabama,Limestone County,82782,82775,83168,...,1266,1389,703,1024,1034,1936,2807,3002,15968,0.191997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,50,3,5,12,119,Florida,Sumter County,93420,93420,94286,...,6075,6144,5869,6293,4454,5593,6049,7087,39486,0.418790
2613,50,3,7,48,91,Texas,Comal County,108472,108525,109311,...,3394,4126,5020,5048,6056,7298,7918,8124,47124,0.431100
2848,50,4,8,49,51,Utah,Wasatch County,23530,23525,23642,...,909,921,958,1007,1272,933,673,837,10568,0.447001
2672,50,3,7,48,209,Texas,Hays County,157107,156978,158086,...,6117,7221,8126,8505,8868,6572,6061,9656,72314,0.457435
2078,50,2,4,38,105,North Dakota,Williams County,22398,22399,22591,...,2488,2098,2671,-1552,-1128,1583,1636,207,15306,0.677526

In [ ]:
absgrowthcty = countieslg.sort_values('totalgrowth').tail(100)

In [ ]:
absgrowthcty

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,NETMIG2013,NETMIG2014,NETMIG2015,NETMIG2016,NETMIG2017,NETMIG2018,NETMIG2019,NETMIG2020,totalgrowth,pctgrowth
1956,50,3,5,37,63,North Carolina,Durham County,267587,269998,271366,...,3656,3869,3295,4693,2192,2914,3457,2585,51603,0.190160
1710,50,2,4,31,55,Nebraska,Douglas County,517110,517120,518599,...,1587,1791,1545,1870,832,1309,142,-429,52261,0.100773
1885,50,1,2,36,47,New York,Kings County,2504700,2504856,2509954,...,-7106,-11990,-19015,-26235,-37955,-37256,-38145,-40985,52375,0.020867
1295,50,2,3,26,81,Michigan,Kent County,602622,602625,602994,...,3991,2777,1817,2760,1582,421,-513,-1494,53806,0.089231
2565,50,3,6,47,187,Tennessee,Williamson County,183182,183208,184082,...,4872,5108,5166,6344,6185,5151,5176,6019,54474,0.295922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2787,50,3,7,48,439,Texas,Tarrant County,1809034,1811345,1818167,...,14857,17178,22558,22006,17021,10709,6905,9813,283115,0.155715
3018,50,4,9,53,33,Washington,King County,1931249,1931289,1938431,...,23449,25275,28744,27392,24521,11815,10297,15054,311222,0.160554
1778,50,4,8,32,3,Nevada,Clark County,1951269,1951278,1952640,...,16274,23743,31733,30635,32165,35623,37597,32824,323244,0.165542
2668,50,3,7,48,201,Texas,Harris County,4092459,4093109,4107542,...,46165,56452,54532,18433,-11605,-19459,-6135,-6412,601701,0.146487
107,50,4,8,4,13,Arizona,Maricopa County,3817117,3817371,3825183,...,43009,48273,52187,59384,48213,56154,67624,70588,667078,0.174391

In [ ]:
sect = pd.merge(propgrowthcty, absgrowthcty, how='inner')

In [ ]:
sect

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,NETMIG2013,NETMIG2014,NETMIG2015,NETMIG2016,NETMIG2017,NETMIG2018,NETMIG2019,NETMIG2020,totalgrowth,pctgrowth
0,50,3,5,37,63,North Carolina,Durham County,267587,269998,271366,...,3656,3869,3295,4693,2192,2914,3457,2585,51603,0.190160
1,50,3,7,48,39,Texas,Brazoria County,313166,313186,314499,...,3217,5071,4895,5486,6527,4949,3014,3918,60200,0.191416
2,50,3,5,12,21,Florida,Collier County,321520,321514,322576,...,6533,7865,8719,9446,7606,5700,7823,8211,63341,0.196360
3,50,3,5,12,57,Florida,Hillsborough County,1229226,1229207,1233511,...,17938,20846,24865,26483,23884,19937,15317,17042,242920,0.196934
4,50,3,5,12,105,Florida,Polk County,602095,602068,603119,...,6164,10307,13169,16466,18464,20454,17419,19536,121848,0.202030
5,50,4,8,8,31,Colorado,Denver County,600158,599454,603012,...,8841,9711,13427,7792,3877,6875,5132,6229,122496,0.203140
6,50,3,5,37,119,North Carolina,Mecklenburg County,919628,919675,923292,...,15134,11208,14381,15063,12875,7767,9370,8214,189991,0.205776
7,50,3,5,12,95,Florida,Orange County,1145956,1145949,1148590,...,16459,20382,25843,27012,21309,17401,3699,1824,246781,0.214856
8,50,4,8,4,21,Arizona,Pinal County,375770,375766,379106,...,1123,7869,8545,9868,12792,13704,13954,18382,82534,0.217707
9,50,2,3,18,57,Indiana,Hamilton County,274569,274555,276499,...,4827,3419,3472,5218,4989,5429,5514,4648,61456,0.222265
10,50,4,8,49,49,Utah,Utah County,516564,516639,520033,...,1813,-56,2631,8258,7122,5463,4499,6213,115642,0.222374
11,50,4,8,16,1,Idaho,Ada County,392365,392364,393369,...,4655,7137,5141,9551,10125,10476,11053,11068,88511,0.225008
12,50,4,8,8,35,Colorado,Douglas County,285465,285480,287011,...,5145,5775,5410,4185,5500,5433,6097,7113,64831,0.225883
13,50,3,5,37,183,North Carolina,Wake County,900993,901036,906875,...,14540,15702,17076,18433,16517,12716,13905,13489,205920,0.227065
14,50,3,5,12,69,Florida,Lake County,297052,297047,297724,...,4769,7648,10528,10629,11530,12366,10996,10122,69217,0.232487
15,50,3,7,48,453,Texas,Travis County,1024266,1024314,1030392,...,14446,18566,16369,15229,11107,9707,18040,18344,243175,0.236002
16,50,3,5,45,91,South Carolina,York County,226073,226033,226871,...,3530,4764,5286,6392,7428,6953,6561,7139,54628,0.240789
17,50,3,5,12,71,Florida,Lee County,618754,618761,620481,...,15296,17073,22262,23381,18239,14546,17993,20504,151787,0.244628
18,50,3,5,12,81,Florida,Manatee County,322833,322879,323442,...,7918,8933,11846,13123,10479,9220,9893,9627,79535,0.245902
19,50,3,7,5,7,Arkansas,Benton County,221339,221348,222601,...,2934,3547,5036,5778,5447,3887,5343,7095,57234,0.257115
20,50,3,6,47,149,Tennessee,Rutherford County,262604,262593,263721,...,4713,5374,7144,7000,7043,6032,5293,5213,68404,0.259380
21,50,4,8,8,123,Colorado,Weld County,252825,252836,254224,...,3747,4913,6568,7271,7716,6363,6907,6924,70479,0.277232
22,50,3,6,47,187,Tennessee,Williamson County,183182,183208,184082,...,4872,5108,5166,6344,6185,5151,5176,6019,54474,0.295922
23,50,3,5,45,51,South Carolina,Horry County,269291,269136,270295,...,7326,8584,11238,12335,12060,11918,10618,12302,84123,0.311227
24,50,3,5,51,107,Virginia,Loudoun County,312311,312342,315486,...,8163,8217,7814,7476,7675,5109,5354,4568,99386,0.315025
25,50,3,7,48,85,Texas,Collin County,782341,780894,787102,...,14242,21004,23580,22163,21771,26793,22993,31495,247970,0.315042
26,50,3,7,48,339,Texas,Montgomery County,455746,455740,459223,...,10386,14972,14822,15575,12620,15316,14344,16069,148360,0.323067
27,50,3,7,48,121,Texas,Denton County,662614,661615,665833,...,14032,17573,19661,21962,20761,17374,25055,25591,222932,0.334817
28,50,3,7,48,157,Texas,Fort Bend County,585375,584632,590177,...,21055,25299,24357,22247,17177,14889,18074,21924,222560,0.377107
29,50,3,5,13,117,Georgia,Forsyth County,175511,175498,176736,...,5757,7298,7363,8183,7166,6775,6104,5404,67888,0.384121
30,50,3,5,12,109,Florida,St. Johns County,190039,190040,191268,...,6981,7867,8136,8330,8770,9786,10989,13790,73800,0.385846
31,50,3,5,12,97,Florida,Osceola County,268685,268685,269841,...,8302,9594,10535,12139,12980,12071,4965,9401,104329,0.386631
32,50,3,7,48,491,Texas,Williamson County,422679,422771,426568,...,10236,13566,15148,16532,14848,16928,20801,22460,165255,0.387406
33,50,3,7,48,209,Texas,Hays County,157107,156978,158086,...,6117,7221,8126,8505,8868,6572,6061,9656,72314,0.457435

In [ ]:
us.columns

Index(['quadkey', 'avg_d_kbps', 'avg_u_kbps', 'avg_lat_ms', 'tests', 'devices',
       'index_righ', 'STATEFP', 'COUNTYFP', 'COUNTYNS', 'GEOID', 'NAME',
       'NAMELSAD', 'LSAD', 'CLASSFP', 'MTFCC', 'CSAFP', 'CBSAFP', 'METDIVFP',
       'FUNCSTAT', 'ALAND', 'AWATER', 'INTPTLAT', 'INTPTLON', 'geometry',
       'STATENAME'],
      dtype='object')

In [ ]:
us[['avg_d_kbps', 'avg_u_kbps', 'avg_lat_ms','NAME', 'STATENAME']].groupby(['STATENAME', 'NAME']).mean()

                         avg_d_kbps    avg_u_kbps  avg_lat_ms
STATENAME NAME
Alabama   Autauga     111177.437500  40532.955000   47.407500
          Baldwin      77741.209245  30603.861829   74.131213
          Barbour      66922.000000   9129.917293   87.721805
          Bibb         42270.964539  28659.184397   76.666667
          Blount       60889.521204  21384.781122   47.896033
...                             ...           ...         ...
Wyoming   Sweetwater   51271.542636  12741.643411   34.139535
          Teton        69657.226506  25032.551807   62.621687
          Uinta        51310.520000  20876.273333   36.193333
          Washakie     52312.328125  20581.203125   24.125000
          Weston       56062.338462  11086.276923   80.461538

[3213 rows x 3 columns]

In [1]:
states = ['Washington', 'North Dakota', 'Arizona', 'Idaho', 'Florida', 'Nevada', 'Colorado', 'Texas', 'Utah']

In [ ]:
for state in states: